# See https://pre-commit.com for more information
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-docstring-first
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: fix-byte-order-marker

- repo: local
  hooks:
  - id: ct-lint
    name: "Chart Test: Lint"
    language: docker_image
    pass_filenames: false
    types: ['file']
    files: '^(stable|incubator)/.*(\.ya?ml|\.tpl|\.helmignore|NOTES.txt)'
    entry: -u 0 quay.io/helmpack/chart-testing:v3.0.0 ct
    args:
    - lint
