image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true

persistence:
  config:
    enabled: true
    emptyDir:
      enabled: true
    mountPath: /www/assets

addons:
  codeserver:
    enabled: true
    workingDir: "/www/assets"
    ingress:
      main:
        enabled: true
    volumeMounts:
    - name: config
      mountPath: /www/assets
